version: '3.4'

services:
 chatdb:
    container_name: chatdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ChatDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
 pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=bong.buibuibong29@hcmut.edu.vn
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
 chatapp.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=ChatDb;Port=5432;Database=ChatDb;User Id=admin;Password=admin1234;"
    depends_on:
      - chatdb
    ports:
      - 5000:80
 
 